@echo off
REM このBATはプロジェクトルートで実行してください。templates配下の旧案・未使用HTMLだけを削除します。
cd /d "%~dp0"
if exist "templates\mobile_order_a.html" del "templates\mobile_order_a.html"
if exist "templates\mobile_order_b.html" del "templates\mobile_order_b.html"
if exist "templates\mobile_order_c.html" del "templates\mobile_order_c.html"
if exist "templates\mobile_order_d.html" del "templates\mobile_order_d.html"
if exist "templates\mobile_order_test_a.html" del "templates\mobile_order_test_a.html"
if exist "templates\mobile_order_test_b.html" del "templates\mobile_order_test_b.html"
if exist "templates\mobile_order_test_c.html" del "templates\mobile_order_test_c.html"
if exist "templates\mobile_order_test_d.html" del "templates\mobile_order_test_d.html"
if exist "templates\mobile_order_test_menu.html" del "templates\mobile_order_test_menu.html"
if exist "templates\mobile_order_test_separate.html" del "templates\mobile_order_test_separate.html"
if exist "templates\mobile_order_button_uniform.html" del "templates\mobile_order_button_uniform.html"
if exist "templates\mobile_order_two_row_layout.html" del "templates\mobile_order_two_row_layout.html"
if exist "templates\mobile_order_test_two_row_layout.html" del "templates\mobile_order_test_two_row_layout.html"
if exist "templates\mobile_order_image_large_ratio.html" del "templates\mobile_order_image_large_ratio.html"
if exist "templates\mobile_order_test_image_large_ratio.html" del "templates\mobile_order_test_image_large_ratio.html"
if exist "templates\mobile_order_fixed_txt_auto_translation.html" del "templates\mobile_order_fixed_txt_auto_translation.html"
if exist "templates\mobile_order_test_fixed_txt_auto_translation.html" del "templates\mobile_order_test_fixed_txt_auto_translation.html"
if exist "templates\mobile_order_runtime_ready.html" del "templates\mobile_order_runtime_ready.html"
if exist "templates\mobile_order_test_runtime_ready.html" del "templates\mobile_order_test_runtime_ready.html"
if exist "templates\patched_mobile_order_runtime_ready.html" del "templates\patched_mobile_order_runtime_ready.html"
if exist "templates\patched_mobile_order_test_runtime_ready.html" del "templates\patched_mobile_order_test_runtime_ready.html"
if exist "templates\mobile_order_real_separate.html" del "templates\mobile_order_real_separate.html"
if exist "templates\mobile_order_button_fixed.html" del "templates\mobile_order_button_fixed.html"
if exist "templates\mobile_placeholder.html" del "templates\mobile_placeholder.html"
if exist "templates\receipt_orders.html" del "templates\receipt_orders.html"
echo 不要HTMLの削除チェックが完了しました。
pause
